### ISSUE TITLE
Unable to login using Custom Domain

### ISSUE THREAD

**Issue by danielmauricio** [auth0-samples/auth0-react-native-sample#36]
### Description

I’m trying to login into my native app and this is what I’m getting: “You should not be hitting this endpoint. Make sure to use the code snippets shown in the tutorial or contact support@auth0.com for help”

At the very beggining I was using the application domain and it was working, but we already have a custom domain (we need to have it), so after I changed the domain in my native app I started getting that error.

Current configuration:
```javascript
const auth0 = new Auth0({
  domain: customDomain,
  clientId: clientID,
  configurationBaseUrl: 'https://cdn.auth0.com',
  overrides: {
    __tenant: 'dev-aura',
    __token_issuer: 'https://${customDomain}'
  }
});
```

**Comment by lbalmaceda** [comment]
That doesn't look like the Auth0 react-native SDK accepted parameters. Are you sure this is the correct repo? If so, what version are you using?

**Comment by danielmauricio** [comment]
At the very beggining I used just:

```javascript
const auth0 = new Auth0({
  domain: customDomain,
  clientId: clientID
});
```
And I was able to log in, but later on I needed to start using my custom domain and everything crashed, so I looked in some community threads:

* https://community.auth0.com/t/custom-domain-with-auth0-js-you-should-not-be-hitting-this-endpoint/22769 
* https://community.auth0.com/t/custom-domain-with-auth0-js-getting-error-you-should-not-be-hitting-this-endpoint/19883/5

Tried to follow the suggestions there and didn't work when I started using my custom domain.


Current version: `"react-native-auth0": "^2.3.0"`.

**Comment by lbalmaceda** [comment]
I might be missing something but, according to the constructor here, other options than `domain` and `clientId` are passed as `extras` to the "Auth" class.
https://github.com/auth0/react-native-auth0/blob/3c47265ac1e64d832fa6c169cfec5b1c859bfdf0/index.js#L22-L23

But then both "Auth" and the networking "Client" don't make use of any of the values you are providing.

https://github.com/auth0/react-native-auth0/blob/3c47265ac1e64d832fa6c169cfec5b1c859bfdf0/src/auth/index.js#L23-L24

https://github.com/auth0/react-native-auth0/blob/3c47265ac1e64d832fa6c169cfec5b1c859bfdf0/src/networking/index.js#L7

Can this be an issue with your customized login page script, instead of the react-native SDK?

**Comment by danielmauricio** [comment]
Yes, I think the issue was in my customized login page script. Thanks!
Now I'm having issues that it doesn't redirect, but I'll try to figure it out.

Thanks!
